### ISSUE TITLE
Next Omnisharp meeting

### ISSUE THREAD

**Issue by sayedihashimi** [OmniSharp/Kulture#18]
Hey guys now that the holidays are behind us let's get together and see where we are all at.

How about ***1/28 at 1 PM Pacific Time***?

I'm looking for the following folks to join minimally.
@shanselman @davidfowl @jchannon @nosami @Mpdreamz @stephen-james @mat-mcloughlin @sp3ctum @bbbscarter @jrieken @chrisdias DustinCampbell

Others who are interested please reply below.

What should we use? Skype? Google hangouts?

**Comment by stephen-james** [comment]
great I'll be there

**Comment by Mpdreamz** [comment]
cool, I'm available then as well.

**Comment by shanselman** [comment]
Cool I'm there.

On Fri, Jan 9, 2015 at 1:07 PM, Martijn Laarman <notifications@github.com>
wrote:

> cool, I'm available then as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OmniSharp/Kulture/issues/18#issuecomment-69399039>.
>



-- 
Scott Hanselman
Donate to fight diabetes: http://hnsl.mn/fightdiabetes

**Comment by nosami** [comment]
Good with me.

**Comment by jchannon** [comment]
I can make it

**Comment by jrieken** [comment]
+1

**Comment by danroth27** [comment]
@sayedihashimi Include me too.

**Comment by sp3ctum** [comment]
Unfortunately that time isn't suitable for me. But that's okay, maybe @nosami can be my liaison regarding emacs stuff :)

**Comment by sayedihashimi** [comment]
FYI we may need to move this to next week. I'm following up with some folks on my side and I will let you know once I have more details.

**Comment by sayedihashimi** [comment]
“Hey guys it looks like we need to move this. @chrisdias has a conflict and is fully booked this week (_with pressing deliverables which are due this Friday_). He has some important items that he would like to discuss so I think it’s important to have him there. He has asked that we all sign NDAs for this particular meeting since he will be sharing some insight into the roadmap of his product which they are not ready to share broadly. Please bear with us, it’ll be worth it :)

How about next Tuesday same time *1/27 at 11 AM Pacific Time*”

**Comment by jchannon** [comment]
Yup fine by me

On 21 January 2015 at 00:27, Sayed Ibrahim Hashimi <notifications@github.com

**Comment by mat-mcloughlin** [comment]
Me too

**Comment by stephen-james** [comment]
Cool

**Comment by sayedihashimi** [comment]
I chatted with @shanselman and we are thinking to use google hangouts for this. If this will not work for you please let us know.

**Comment by sayedihashimi** [comment]
Everyone, please email 📧 me your Google ID so that we can get you added to the hangout. sayedha @ MSFT

**Comment by nosami** [comment]
I'll be there

**Comment by sayedihashimi** [comment]
Hey guys sorry for the back and forth here. This is going to be a special meeting and I've been having a hard time scheduling it to get everyone lined up.

We are going to have a special guest for the next meeting, Erich Gamma (@egamma), and the 11 AM PT time slot doesn't work for him (_on any day_). He is not available on 1/27 and has asked if we can move the meeting to ***1/29 at 1PM PT***. I'm not sure what timezone everyone is in so I'm not sure if this is too late or not. If it is too late we can try for the 8-9 AM PT time slot on 1/29.

Does ***1/29 at 1PM PT*** work?

Thanks

**Comment by nosami** [comment]
Hmmm.... I can't make Thursday or Friday this week

**Comment by sayedihashimi** [comment]
@nosami, how about Wednesday ***1/28 at 1PM PT***?

**Comment by nosami** [comment]
That works!

**Comment by sayedihashimi** [comment]
@nosami thanks I've updated the comment above to use 1/28 and I'll delete the two previous messages about Thrusday/Friday not working to make it easier for other folks. Will delete this message as well.

**Comment by jchannon** [comment]
Yup I can do that. Its 9pm UK so guess thats 10pm for @Mpdreamz

**Comment by mat-mcloughlin** [comment]
yeah I'm ok with that

**Comment by jrieken** [comment]
:+1:

**Comment by sp3ctum** [comment]
Sorry, that is too late for me. One or two hours earlier would have been
fine.
I realize it's difficult to organize world wide meetings, so maybe I'll
join next time.

2015-01-27 9:33 GMT+02:00 Mathew McLoughlin <notifications@github.com>:

**Comment by markrendle** [comment]
I'd like to attend if that's OK.

**Comment by Yantrio** [comment]
I would also like to attend if possible :)

**Comment by filipw** [comment]
I'd love to be able to join too - if that's all right

**Comment by Mpdreamz** [comment]
I'll take a nap beforehand, 10 works for me :)

**Comment by sayedihashimi** [comment]
Thanks for the interest in the meeting. Typically our meetings are completely open and community driven. In this ***rare occurrence*** we have some folks from Microsoft that are going to be sharing some future plans which they are not ready to share broadly. Since the topic will impact ```omnisharp-rosyln``` they have asked to have an NDA conversation with core Omnisharp contributors. Because of that ***we are limiting this one meeting to NDAed OmniSharp contributors***.

@Yantrio I know that you are a contributor so please email me the following info.
 - google email address
 - Your full name
 - Your mailing address
to sayedha@microsoft.com

I will need you an NDA on file if you do not already before the meeting.

@markrendle @filipw if you have given feature contributions that I'm not aware of then email me the info above as well as the OmniSharp features which you've implemented. If you are not an active contributor then I ask that you attend the next meeting which will be completely open.

Once again typically our meetings are completely open and community driven. This is a special meeting where we cannot do that, but we strive to be as open as possible. This is the exception not the rule.

**Comment by sayedihashimi** [comment]
I still need google IDs from the following folks.

 - [ ] @stephen-james 
 - [ ] @mat-mcloughlin 
 - [ ] @bbbscarter 

Once we have those I think we are all set for tomorrow

**Comment by egamma** [comment]
Hi

in case you do not have mine. I'm erich.gamma@gmail.com

--erich

**Comment by mat-mcloughlin** [comment]
mathew.mcloughlin@gmail.com

**Comment by sayedihashimi** [comment]
Thanks for the meeting guys. Me and @chrisdias will be following up individually with folks. Closing this now.
