### ISSUE TITLE
Build command is run with sh instead of bash, which causes problems in Linux Mint

### ISSUE THREAD

**Issue by Andorbal** [OmniSharp/Kulture#19]
I installed Sublime Text 3, Kulture, and OmniSharp on a fresh install of Linux Mint 17.  When I try to build an aspnet vNext project, I get the following output in Sublime:

```
[Finished in 0.0s with exit code 2]
[cmd: ['sh', '/home/andrew/.config/sublime-text-3/Packages/Kulture/build.sh']]
[dir: /home/andrew/.config/sublime-text-3/Packages/Kulture]
[path: /home/andrew/work/yii/framework:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games]/home/andrew/.config/sublime-text-3/Packages/Kulture/build.sh: 363: /home/andrew/.kre/kvm/kvm.sh: Syntax error: "(" unexpected (expecting ";;")
```

I found an [article](https://wiki.ubuntu.com/DashAsBinSh) that describes the behavior I'm seeing: since the command is run with `sh` and that is linked to `dash` by default, the command fails.  If I change ASP.NET.sublime-build to explicitly use `bash` instead of `sh`, the build works as expected.

Is there a reason that bash is not explicitly used?  I'm happy to submit a pull request, but I wanted to see if this is a change that should be made before doing it.

**Comment by sayedihashimi** [comment]
It was not on purpose, we are not Linux experts. If you can help there it would be greatly appreciated.

**Comment by nosami** [comment]
Not sure if you can guarantee that bash is even installed. Should probably
check for bash or zsh.

**Comment by Andorbal** [comment]
I'm not a Linux expert either, and I agree with @nosami that you typically shouldn't expect the user has a specific shell installed.  That said, it looks like OmniSharp and ksh lean towards bash.

I'm going to see if I have time tonight to look at ways of mitigating the issue without just changing "sh" to "bash."  Looking at Sublime's [documentation](http://docs.sublimetext.info/en/latest/reference/build_systems.html), it looks like we might be able to use "build.sh" and use the shell option to let the OS sort out what shell to use.

I can test against Linux Mint 17, MacOS Mavericks, and Windows 8.1 and submit a pull request if it works.

**Comment by Andorbal** [comment]
I've created a pull request ( #20 ) that changes the shell that should be used to bash.

**Comment by sayedihashimi** [comment]
Merged the PR closing this now
