### ISSUE TITLE
KPM install not working correctly

### ISSUE THREAD

**Issue by skotzko** [OmniSharp/Kulture#28]
I'm trying to get up and running w/ OmniSharp (using Sublime as editor) but running into issues w/ K / KPM. I'm on Yosemite 10.10.3.

What I've done:

1. Installed the ASP.NET 5 command line tools (using the latest `brew tap aspnet/dnx; brew install dnvm` instructions after the rename from `aspnet/k`, per [this StackOverflow post](https://stackoverflow.com/questions/29398877/how-do-you-install-dnx-on-osx-using-homebrew))
1. Installed Kulture plugin
1. Installed OmniSharp plugin

DNVM and DNX are installed and functioning, but K/KPM not working (command not found). How do I get them installed correctly?

\### 

Extra info:

- `dnvm` version: `Version 1.0.0-beta5-10371`
- Installed versions of runtimes:

```
~ $ dnvm list

Active Version              Runtime Arch Location             Alias
------ -------              ------- ---- --------             -----
  *    1.0.0-beta5-11631    mono         ~/.dnx/runtimes      default
```
- I also have Mono installed w/ Xamarin Studio. When I run `mono --version` from command line, I get `4.0.1`. But I was under the impression that DNVM installed a separate version of Mono for its use.

**Comment by henkmollema** [comment]
Why do you still need k/kpm?

`k` -> `dnx`
`kvm` -> `dnvm`
`kpm` -> `dnu`

**Comment by skotzko** [comment]
I guess I don't. Apologies, I'm not up to date on the history of changes and what all the tools are. I'm new to vNext and OmniSharp.

So,  when I see `k ___` or `kpm ___` commands, I should swap in `dnx` and `dnu` instead? 

e.g. `kpm build` => `dnu build`?

**Comment by henkmollema** [comment]
Correct!

The most used scenarios are:
`dnvm upgrade` -> upgrade the runtime
`dnu restore` -> restore the packages
`dnu build`
`dnx . web` run the `web` command from the `project.json`. Notice the `.` in the middle.

**Comment by skotzko** [comment]
Ah, got it. Thanks!
