### ISSUE TITLE
Next Omnisharp meeting

### ISSUE THREAD

**Issue by sayedihashimi** [OmniSharp/Kulture#32]
Hi everyone, it's been a while since we last met. We have some exciting news that we'd like to share. 

Can we meet on Skype Monday ***5/18 at 11 AM Pacific Time***?

People that I'm interested in joining include.

@jchannon @nosami @Mpdreamz @stephen-james @mat-mcloughlin @sp3ctum @bbbscarter @jrieken @chrisdias @DustinCampbell @shanselman @davidfowl

**Comment by jchannon** [comment]
Yup good with me!

**Comment by jchannon** [comment]
Including @yantrio

**Comment by sp3ctum** [comment]
Yes, I think I can finally make it! :)
14.5.2015 5.05 ip. "Jonathan Channon" <notifications@github.com> kirjoitti:

**Comment by mat-mcloughlin** [comment]
yeah, I'll come

**Comment by Mpdreamz** [comment]
I'm travelling that day but hopefully will be able to make it :)  @david-driscoll @ctolkien have been killing it with atom lately please include them as well :+1:

**Comment by sayedihashimi** [comment]
@nosami how about you?

>I'm travelling that day but hopefully will be able to make it :) @david-driscoll @ctolkien have been killing it with atom lately please include them as well

Sure they are welcome to join as well.

**Comment by david-driscoll** [comment]
Sounds interesting, I should be able to be online.

If you need my skype id let me know.

**Comment by nosami** [comment]
Yeah. Count me in.

**Comment by ctolkien** [comment]
That's about 4am local time so I'll have to pass!

**Comment by bbbscarter** [comment]
I won’t be able to make it, I’m afraid (I’m out all evening). Look forward to seeing any notes though!

Simon



On 15 May 2015 at 00:01:44, Chad T (notifications@github.com) wrote:

That's about 4am local time so I'll have to pass!

**Comment by Yantrio** [comment]
I can make it :)

**Comment by jrieken** [comment]
+1

**Comment by stephen-james** [comment]
Hey guys, afraid I can't make it tonight, but will catch up with some of the others in the next couple of days  :)

**Comment by sayedihashimi** [comment]
If you're planning to attend I'll need to email you a link to join. I have emails for the people listed below. If you want to attend and are not listed email me your email address sayedha@microsoft.com.

 - Jason Imison
 - Jonathan Channon
 - Stephen James
 - Martijn Laarman
 - Mika Vilpas
 - Mathew McLoughlin
 - Simon Carter
 - James Humphries

**Comment by sayedihashimi** [comment]
OK I have sent a link to the email addresses above.

@david-driscoll I need your email address so that I can share the link with you.

**Comment by david-driscoll** [comment]
Sent!

**Comment by sayedihashimi** [comment]
@david-driscoll thanks, I've sent you the link.

**Comment by sayedihashimi** [comment]
Notes from the meeting are at https://github.com/OmniSharp/Kulture/wiki/meeting-2015.05.21
